---
title: "organizaciones"
author: "NLMR"
date: "22/2/2022"
output: html_document
---

```{r, include=F, warning=F, echo=F}
library(readxl)
library(viridis)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyverse)
library(DT)
library(plotly)


organizaciones <- read_excel("Respuestas Organizaciones.xlsx", sheet = "Para procesar")

```



```{r, include=F, warning=F, echo=F}

organizaciones %>% 
  group_by(`...9`) %>% 
  summarise(Medicamentos=n())

```



```{r, include=F, warning=F, echo=F}

organizaciones %>% 
  group_by(`...13`) %>% 
  summarise(Medicamentos=n(),
            Porcentaje= percent(Medicamentos/37)) %>% 
   filter(!(`...13`=="NA")) %>%
  ggplot(aes(x = reorder(`...13`, -Medicamentos),
           y= Porcentaje ,fill = `...13`)) +
  geom_col()+
  coord_flip() +
  geom_text(aes(x=`...13`, y=Porcentaje, 
                label=Porcentaje),
            colour="black", size=5,
            hjust=-1, vjust=.5, angle=0)+
  scale_fill_viridis_d(option = "viridis", direction = 1) +
    labs(x="", y="", fill="")+
theme_minimal() +
  theme(legend.position = "bottom")+
  theme(strip.background = element_rect(color="black", fill="white", size=1.5),
        strip.placement = 'outside',
        strip.background.x = element_blank(),
        strip.text.x = element_text(size = 15, face = "bold", angle=0))+
  theme(panel.grid.minor.x = element_blank(),
        panel.spacing.x = unit(0,"line")) +
  theme(axis.text.x = element_text(angle = 0, hjust=.5, size=15, face="bold"),
        axis.text = element_text(size = 15, colour="black"))->pacientes



ggsave(pacientes, filename = "pacientes.png", width = 35, height = 25, units = "cm", dpi = 96)


```



```{r, include=F, warning=F, echo=F}

organizaciones %>% 
  summarise(
    `2017`= mean(`¿Cuánto gastó su organización en la compra de medicamentos en 2017?`, na.rm=T),
    `2018`= mean(`¿Cuánto gastó su organización en la compra de medicamentos en 2018?`, na.rm=T),
    `2019`= mean(`¿Cuánto gastó su organización en la compra de medicamentos en 2019?`, na.rm=T),
    `2020`= mean(`¿Cuánto gastó su organización en la compra de medicamentos en 2020?`, na.rm=T),
    `2021`= mean(`¿Cuánto gastó su organización en la compra de medicamentos en 2021?`, na.rm=T)) %>% 
        pivot_longer(names_to="Gasto en medicamentos por año",
                 values_to ="TOTAL",
                 cols = c("2017",
                          "2018",
                          "2019",
                          "2020",
                          "2021")) %>% 
    ggplot(aes(x=`Gasto en medicamentos por año`, y=TOTAL, group=1))+
  geom_point(size=5, colour="#51BC33")+
  geom_line(size=3, colour="#51BC33")+
  geom_text(aes(x=`Gasto en medicamentos por año`, y=TOTAL, 
                   label=comma(TOTAL, accuracy = 1.0),
                hjust=.5, vjust=-1, size=5))+
  labs(x="", y="", fill="")+
 scale_y_continuous(labels = scales::comma) +  

  theme_minimal() +
  theme(legend.position = "bottom")+
  theme(strip.background = element_rect(color="black", fill="white", size=1.5),
        strip.placement = 'outside',
        strip.background.x = element_blank(),
        strip.text.x = element_text(size = 15, face = "bold", angle=0))+
  theme(panel.grid.minor.x = element_blank(),
        panel.spacing.x = unit(0,"line")) +
  theme(axis.text.x = element_text(angle = 0, hjust=.5, size=15, face="bold"),
        axis.text = element_text(size = 15, colour="black"))->lin_gasto



ggsave(lin_gasto, filename = "lin_gasto.png", width = 40, height = 25, units = "cm", dpi = 96)



```







```{r, include=F, warning=F, echo=F}


organizaciones %>% 
  group_by(`A aumentado desde cuando`) %>% 
  summarise(Aumento=n(),
            Porcentaje= percent(Aumento/37)) %>% 
   filter(!(`A aumentado desde cuando`=="NA")) ->aumento_org


aumento_org$`A aumentado desde cuando` <- as.factor(aumento_org$`A aumentado desde cuando`)
aumento_org$Porcentaje <- as.integer(aumento_org$Porcentaje)


aumento_org%>%
  ggplot(aes(x = `A aumentado desde cuando`,
           y= Aumento,
           fill = `A aumentado desde cuando`)) +
  geom_col()+
  geom_text(aes(x=`A aumentado desde cuando`, y=as.numeric(Porcentaje), 
                label=Porcentaje),
            colour="black", size=5,
            hjust=.5, vjust=-1, angle=0)+
  scale_fill_viridis_d(option = "viridis", direction = 1) +
    labs(x="", y="", fill="")+
theme_minimal() +
  theme(legend.position = "none")+
  theme(strip.background = element_rect(color="black", fill="white", size=1.5),
        strip.placement = 'outside',
        strip.background.x = element_blank(),
        strip.text.x = element_text(size = 15, face = "bold", angle=0))+
  theme(panel.grid.minor.x = element_blank(),
        panel.spacing.x = unit(0,"line")) +
  theme(axis.text.x = element_text(angle = 0, hjust=.5, size=15, face="bold"),
        axis.text = element_text(size = 15, colour="black"))->aumento

ggsave(aumento, filename = "aumento.png", width = 35, height = 25, units = "cm", dpi = 96)




```
